---
- name: aur.yml - install packages from AUR
  hosts: local
  
  tasks:
    - name: Install yay to get started
      kewlfft.aur.aur:
        name: yay

    - name: Install AUR packages using yay
      kewlfft.aur.aur:
        name:
          - paru-bin
          - pamac-aur
          - gnome-network-displays
          - kora-icon-theme
          - google-chrome
          - visual-studio-code-bin
          - dropbox
          - nautilus-dropbox
          - turtle
          - wike
          - zoom
          - teams-for-linux
          - gitkraken
          - nordvpn-bin
          - extension-manager
          - menulibre
          - localsend-bin
          - spotify
          - dynalist-desktop
          - obsidian
          - searchmonkey-gtk
          - get_iplayer
        state: present
        use: yay
