---
- name: aur.yml - install packages from AUR
  hosts: local
  
  tasks:
    - name: Install yay to get started
      kewlfft.aur.aur:
        name: yay

    - name: Install AUR packages using yay
      kewlfft.aur.aur:
        name:
          - paru-bin
          - pamac-aur
          - downgrade
          - google-chrome
          - visual-studio-code-bin
          - typora
          - pandoc-bin
          - dropbox
          - wike
          - zoom
          - teams-for-linux
          - sublime-merge
          - nordvpn-bin
          - menulibre
          - localsend-bin
          - spotify
          - dynalist-desktop
          - obsidian
          - get_iplayer
          - uxplay
        state: present
        use: yay
