---
- name: core.yml - Arch Linux base setup
  hosts: local
  become: yes
  
  tasks:
    - name: Update Arch
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Install essential packages
      pacman:
        update_cache: yes
        name:
          - less
          - usbutils
          - bluez-utils
          - fwupd
          - fwupd-efi
          - hwinfo
          - dosfstools
          - gocryptfs
          - bind
          - p7zip
          - unzip
          - ripgrep
          - ripgrep-all
          - xclip
          - pacman-contrib
          - flatpak
          - cups
          - cups-pdf
          - catfish
          - fastfetch
          - nvtop
          - geoclue
          - base-devel
          - clang
          - cmake
          - ninja
          - git
          - difftastic
          - jq
          - bitwarden
          - imagemagick
          - gimp
          - inkscape
          - glow
          - libreoffice-fresh
          - libreoffice-fresh-en-gb
          - hunspell
          - hunspell-en_gb
          - hunspell-en_us
          - hyphen
          - hyphen-en
          - scribus
          - pdfarranger
          - img2pdf
          - mupdf
          - pdftk
          - celluloid
          - mpv
          - vlc
          - streamlink
          - yt-dlp
          - audacity
          - sox
          - atomicparsley
          - cdrdao
          - firefox
          - firefox-i18n-en-gb
          - thunderbird
          - thunderbird-i18n-en-gb
          - filezilla
          - remmina
          - freerdp
          - uv
          - python-psutil
          - android-tools
          - android-udev
          - ttf-opensans
          - wl-clipboard
          - freeplane
          - jre11-openjdk
        state: present

    - name: Start and enable CUPS service
      systemd:
        name: cups
        state: started
        enabled: yes
