---
- name: core.yml - Arch Linux base setup
  hosts: local
  become: yes
  
  tasks:
    - name: Update Arch
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Remove unwanted packges
      pacman:
        name:
          - gnome-calendar
          - gnome-contacts
          - gnome-shell-extensions
          - evolution-data-server
        state: absent
        
    - name: Install essential packages
      pacman:
        update_cache: yes
        name:
          - dconf-editor
          - usbutils
          - bluez-utils
          - fwupd
          - fwupd-efi
          - p7zip
          - xclip
          - pacman-contrib
          - flatpak
          - cups
          - cups-pdf
          - gnome-terminal
          - gnome-themes-extra
          - python-nautilus
          - catfish
          - ghex
          - eog
          - fastfetch
          - base-devel
          - git
          - bitwarden
          - imagemagick
          - gimp
          - gcolor3
          - gedit
          - gedit-plugins
          - glow
          - libreoffice-fresh
          - libreoffice-fresh-en-gb
          - pdfarranger
          - img2pdf
          - mupdf
          - pdftk
          - celluloid
          - mpv
          - vlc
          - streamlink
          - yt-dlp
          - audacity
          - firefox
          - firefox-i18n-en-gb
          - thunderbird
          - thunderbird-i18n-en-gb
          - filezilla
          - remmina
          - transmission-gtk
          - python-psutil
          - android-tools
          - android-udev
        state: present

    - name: Start and enable CUPS service
      systemd:
        name: cups
        state: started
        enabled: yes
        
    - name: Add current user to video group - workaround for https://gitlab.gnome.org/GNOME/snapshot/-/issues/48
      user:
        name: "{{ lookup('env', 'USER') }}"
        groups: video
        append: yes
