---
- name: core.yml - Arch Linux base setup
  hosts: local
  become: yes
  
  tasks:
    - name: Update Arch
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Install essential packages
      pacman:
        update_cache: yes
        name:
          - usbutils
          - bluez-utils
          - fwupd
          - fwupd-efi
          - p7zip
          - ripgrep
          - ripgrep-all
          - xclip
          - pacman-contrib
          - flatpak
          - cups
          - cups-pdf
          - catfish
          - fastfetch
          - nvtop
          - base-devel
          - git
          - bitwarden
          - imagemagick
          - gimp
          - inkscape
          - glow
          - libreoffice-fresh
          - libreoffice-fresh-en-gb
          - scribus
          - pdfarranger
          - img2pdf
          - mupdf
          - pdftk
          - celluloid
          - mpv
          - vlc
          - streamlink
          - yt-dlp
          - audacity
          - sox
          - atomicparsley
          - firefox
          - firefox-i18n-en-gb
          - thunderbird
          - thunderbird-i18n-en-gb
          - filezilla
          - remmina
          - python-psutil
          - android-tools
          - android-udev
          - ttf-opensans
        state: present

    - name: Start and enable CUPS service
      systemd:
        name: cups
        state: started
        enabled: yes
