---
- name: dotnet.yml - packages for .NET execution and development
  hosts: local
  become: yes
  
  tasks:
    - name: Update Arch
      pacman:
        update_cache: yes
        upgrade: yes
        
    - name: Install .NET packages
      pacman:
        update_cache: yes
        name:
          - dotnet-host
          - dotnet-runtime
          - dotnet-sdk
          - dotnet-targeting-pack
          - dotnet-runtime-6.0
          - dotnet-sdk-6.0
          - dotnet-targeting-pack-6.0
        state: present        
