---
- name: dotnet.yml - packages for .NET execution and development
  hosts: localhost
  connection: local
  become: yes
  
  tasks:
    - name: Update Arch
      pacman:
        update_cache: yes
        upgrade: yes
        
    - name: Install .NET packages
      pacman:
        update_cache: yes
        name:
          - dotnet-host                # .NET host resolver
          - dotnet-runtime             # current .NET runtime
          - dotnet-sdk                 # current .NET SDK
          - dotnet-targeting-pack      # current targeting pack
        state: present        
