---
- name: flatpak.yml - install flatpaks
  hosts: local
  become: yes
  
  tasks:
    - name: Ensure Flathub remote exists
      flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: system

    - name: Install flatpaks
      flatpak:
        name:
          - com.github.tchx84.Flatseal
          - io.github.flattool.Warehouse
          - com.anydesk.Anydesk
          - org.qgis.qgis/x86_64/stable
        state: present
        remote: flathub
        method: system

    - name: Ensure GNOME flatpaks look good even when running with other DEs
      pacman:
        update_cache: yes
        name:
          - xdg-desktop-portal-gtk
        state: present
