---
- name: flatpak.yml - install flatpaks
  hosts: local
  become: yes
  
  tasks:
    - name: Ensure Flathub remote exists
      flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: system

    - name: Install flatpaks
      flatpak:
        name:
          - com.github.tchx84.Flatseal                # manage Flatpak app permissions
          - io.github.flattool.Warehouse              # Flatpak package manager GUI
          - com.anydesk.Anydesk                       # remote desktop client
          - com.github.IsmaelMartinez.teams_for_linux # Microsoft Teams client
          - org.qgis.qgis/x86_64/stable               # GIS and mapping suite
          - org.gnome.Papers                          # GNOME document viewer
          - org.gnome.gitlab.somas.Apostrophe         # Markdown editor
          - com.github.zocker_160.SyncThingy          # Syncthing GUI client
          - org.stellarium.Stellarium                 # planetarium software
        state: present
        remote: flathub
        method: system

    - name: Ensure GNOME flatpaks look good even when running with other DEs
      pacman:
        update_cache: yes
        name:
          - xdg-desktop-portal-gtk  # GTK portal backend
        state: present
