---
- name: flatpak.yml - install flatpaks
  hosts: local
  become: yes
  
  tasks:
    - name: Install flatpaks
      flatpak:
        name:
          - io.github.flattool.Warehouse
          - com.anydesk.Anydesk
          - org.freeplane.App
          - org.qgis.qgis/x86_64/stable
          - re.sonny.Workbench
        state: present
