---
- name: games.yml - a few games
  hosts: localhost
  connection: local
  become: yes
  
  tasks:
    - name: Update Arch
      pacman:
        update_cache: yes
        upgrade: yes
        
    - name: Install games
      pacman:
        update_cache: yes
        name:
          - openttd           # OpenTTD game
          - openttd-opengfx   # OpenTTD free graphics set
          - openttd-opensfx   # OpenTTD free sound set
        state: present
