---
- name: games.yml - a few games
  hosts: local
  become: yes
  
  tasks:
    - name: Update Arch
      pacman:
        update_cache: yes
        upgrade: yes
        
    - name: Install games
      pacman:
        update_cache: yes
        name:
          - openttd
          - openttd-opengfx
          - openttd-openmsx
          - openttd-opensfx
        state: present
