---
- name: gnome_conf.yml - configure GNOME settings
  hosts: localhost
  connection: local
  gather_facts: no
  
  tasks:
    - name: Show day of week in top bar
      community.general.dconf:
        key: "/org/gnome/desktop/interface/clock-show-weekday"
        value: "true"
        
    - name: Show seconds in top bar
      community.general.dconf:
        key: "/org/gnome/desktop/interface/clock-show-seconds"
        value: "true"

    - name: Show battery % in top bar
      community.general.dconf:
        key: "/org/gnome/desktop/interface/show-battery-percentage"
        value: "true"

    - name: Disable hot corner
      community.general.dconf:
        key: "/org/gnome/desktop/interface/enable-hot-corners"
        value: "false"

    - name: Show maximize and minimize buttons in window borders
      community.general.dconf:
        key: "/org/gnome/desktop/wm/preferences/button-layout"
        value: "'appmenu:minimize,maximize,close'"

    - name: Enable dark theme
      community.general.dconf:
        key: "/org/gnome/desktop/interface/color-scheme"
        value: "'prefer-dark'"
        
    - name: Enable dark theme (legacy apps)
      community.general.dconf:
        key: "/org/gnome/desktop/interface/gtk-theme"
        value: "'Adwaita-dark'"
        
    - name: Show option in Nautilus to create link
      community.general.dconf:
        key: "/org/gnome/nautilus/preferences/show-create-link"
        value: "true"
        
    - name: Show option in Nautilus to delete permanently
      community.general.dconf:
        key: "/org/gnome/nautilus/preferences/show-delete-permanently"
        value: "true"

    - name: Show tree view in list view in Nautilus
      community.general.dconf:
        key: "/org/gnome/nautilus/list-view/use-tree-view"
        value: "true"
        
    - name: Prevent sleep on AC power
      community.general.dconf:
        key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type"
        value: "'nothing'"
        
    - name: Prevent sleep on battery power
      community.general.dconf:
        key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-battery-type"
        value: "'nothing'"

    - name: Power button should turn off
      community.general.dconf:
        key: "/org/gnome/settings-daemon/plugins/power/power-button-action"
        value: "'interactive'"

    - name: Set screen power off time (15 minutes)
      community.general.dconf:
        key: "/org/gnome/desktop/session/idle-delay"
        value: "uint32 900"   

