---
- name: gnome_flatpak.yml - install GNOME specific flatpaks
  hosts: localhost
  connection: local
  become: yes
  
  tasks:
    - name: Ensure Flathub remote exists
      flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: system

    - name: Install flatpaks
      flatpak:
        name:
          - com.mattjakeman.ExtensionManager   # manage GNOME Shell extensions
          - re.sonny.Workbench                 # GNOME developer sandbox
        state: present
        remote: flathub
        method: system
