---
- name: gnome_conf.yml - configure GNOME settings
  hosts: local
  gather_facts: no
  
  tasks:
    - name: show day of week
      community.general.dconf:
        key: "/org/gnome/desktop/interface/clock-show-weekday"
        value: "true"
        
    - name: show seconds
      community.general.dconf:
        key: "/org/gnome/desktop/interface/clock-show-seconds"
        value: "true"

    - name: show battery %
      community.general.dconf:
        key: "/org/gnome/desktop/interface/show-battery-percentage"
        value: "true"

    - name: disable hot corner
      community.general.dconf:
        key: "/org/gnome/desktop/interface/enable-hot-corners"
        value: "false"

    - name: show maximize and minimize buttons
      community.general.dconf:
        key: "/org/gnome/desktop/wm/preferences/button-layout"
        value: "'appmenu:minimize,maximize,close'"

    - name: enable dark theme
      community.general.dconf:
        key: "/org/gnome/desktop/interface/color-scheme"
        value: "'prefer-dark'"
        
    - name: enable dark theme (legacy)
      community.general.dconf:
        key: "/org/gnome/desktop/interface/gtk-theme"
        value: "'Adwaita-dark'"
        
    - name: show option to create link
      community.general.dconf:
        key: "/org/gnome/nautilus/preferences/show-create-link"
        value: "true"
        
    - name: show option to delete permanently
      community.general.dconf:
        key: "/org/gnome/nautilus/preferences/show-delete-permanently"
        value: "true"

    - name: show tree view in list
      community.general.dconf:
        key: "/org/gnome/nautilus/list-view/use-tree-view"
        value: "true"
        
    - name: prevent sleep on AC power
      community.general.dconf:
        key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type"
        value: "'nothing'"
        
    - name: prevent sleep on battery power
      community.general.dconf:
        key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-battery-type"
        value: "'nothing'"

    - name: power button should turn off
      community.general.dconf:
        key: "/org/gnome/settings-daemon/plugins/power/power-button-action"
        value: "'interactive'"

    - name: set screen power off time
      community.general.dconf:
        key: "/org/gnome/desktop/session/idle-delay"
        value: "uint32 900"   

