---
- name: gnome_aur.yml - install GNOME specific packages from AUR
  hosts: localhost
  connection: local
  
  tasks:
    - name: Install yay to get started
      kewlfft.aur.aur:
        name: yay # AUR helper

    - name: Install AUR packages using yay
      kewlfft.aur.aur:
        name:
          - gnome-network-displays   # Miracast/Wi-Fi display support
          - kora-icon-theme          # icon theme
          - nautilus-dropbox         # Dropbox integration for Nautilus
          - turtle                   # Git integration for Nautilus
        state: present
        use: yay
