---
- name: kde_aur.yml - install KDE specific packages from AUR
  hosts: localhost
  connection: local
  
  tasks:
    - name: Install yay to get started
      kewlfft.aur.aur:
        name: yay # AUR helper

    - name: Install AUR packages using yay
      kewlfft.aur.aur:
        name:
          - plasma6-applets-arch-update-notifier   # Arch update notifier widget
        state: present
        use: yay
