---
- name: kde_aur.yml - install KDE specific packages from AUR
  hosts: local
  
  tasks:
    - name: Install yay to get started
      kewlfft.aur.aur:
        name: yay

    - name: Install AUR packages using yay
      kewlfft.aur.aur:
        name:
          - plasma6-applets-arch-update-notifier
        state: present
        use: yay
