---
- name: kvm_qemu.yml - set up KVM and QEMU for virtualization
  hosts: local
  become: yes

  tasks:
    - name: Update Arch
      pacman:
        update_cache: yes
        upgrade: yes
        
    - name: Install necessary packages for KVM and QEMU
      pacman:
        name:
          - iptables-nft    # nftables backend for iptables
          - qemu-desktop    # QEMU system emulator
          - virt-manager    # libvirt VM manager GUI
          - virt-viewer     # VM console viewer
          - dnsmasq         # DHCP/DNS for libvirt networks
          - vde2            # virtual network switch
          - bridge-utils    # network bridge tools
          - openbsd-netcat  # netcat utility
        state: present
        
    - name: Start and enable libvirtd service
      systemd:
        name: libvirtd
        state: started
        enabled: yes

    - name: Add current user to libvirt group
      user:
        name: "{{ lookup('env', 'USER') }}"
        groups: libvirt
        append: yes

    - name: Add current user to kvm group
      user:
        name: "{{ lookup('env', 'USER') }}"
        groups: kvm
        append: yes
