---
- name: virtio-win.yml - install KVM/QEMU virtualization drivers for Windows
  hosts: local
  
  tasks:
    - name: Install yay to get started
      kewlfft.aur.aur:
        name: yay # AUR helper

    - name: Install virtio drivers for Windows
      kewlfft.aur.aur:
        name:
          - virtio-win   # virtio driver ISO for Windows guests
        state: present
        use: yay
